name: FKeyCommand
version: 2.0
main: org.cikerr.fkeycommand.FKeyCommand
api-version: 1.16
commands:
  fkc:
    description: FKeyCommand plugin commands
    usage: /<command> <reload>
permissions:
  fkc.use:
    description: Allows using the FKeyCommand swap hand items feature
    default: op
  fkc.reload:
    description: Allows reloading the FKeyCommand configuration
    default: op
